### PR TITLE
Extended with Batching

### PR DESCRIPTION
**Pull request by frankmcsherry**
Hihihihihihihi.

I've added a few things to the example that may make it more exciting to test. 

There are two new parameters:

`-b` indicates an amount of physical batching. The same computation is performed in either case, but setting a large number here will let differential dataflow do a bit more concurrent work. The default is 1,000.

`-w` indicates a number of timely dataflow workers. This should probably be some small number, no more than the number of cores you have.

I also linked up the `-r` argument so that we can spend fewer than sixty seconds.

Example output:

```
Echidnatron% cargo run --release -- -b1000 -r10 -w2
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/eintopf -b1000 -r10 -w2`
Loading finished after Duration { secs: 0, nanos: 122132778 }
worker 0: 5024001 in 10.000586984s => 502370.60848414013
Done
Echidnatron%
```

### CODE REVIEW

**Comment by frankmcsherry** [comment]
The output above was from a single-threaded run (back in the days when we didn't read the `-w` argument). Here is some more representative output

```
Echidnatron% cargo run --release -- -b1000 -r10 -w2
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/eintopf -b1000 -r10 -w2`
Loading finished after Duration { secs: 0, nanos: 99246378 }
Loading finished after Duration { secs: 0, nanos: 99246053 }
worker 0: 8448001 in 10.013789528s => 843636.7543586622
worker 1: 8448001 in 10.013763393s => 843638.9565098409
Done
Echidnatron%
```

Note that the counts and throughputs are for the total computation, not the work done by each worker. They each count up to a number but only do their fraction of the work.

**Comment by frankmcsherry** [comment]
The workers now properly share responsibility for pushing data once the computation is up and running. This has a nominal impact with two workers, but it would presumably get out of hand with larger numbers.

```
Echidnatron% cargo run --release -- -b1000 -r10 -w2
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/eintopf -b1000 -r10 -w2`
Loading finished after Duration { secs: 0, nanos: 78896602 }
Loading finished after Duration { secs: 0, nanos: 78897532 }
worker 0: 9152001 in 10.006336334s => 914620.5548012428
worker 1: 9152001 in 10.006390938s => 914615.5676358774
Done
Echidnatron%
```

**Comment by ms705** [comment]
Hmm, I think this is still not entirely correct: workers now share the responsibility for introducing *votes* at runtime, but still each write 100,000 articles in the prepopulation phase, no?

**Comment by frankmcsherry** [comment]
Erm, line 123 for me is `if index == 0 {` which guards the introduction of the initial data. This should mean that only worker 0 does this work. It isn't shared between workers, but only one worker should do it.

**Comment by ms705** [comment]
Ah, you're quite right -- I got misled by both workers printing the "Loading finished" message and skimming the diff incorrectly.

**Pull request merged**
